#!/usr/bin/env -S uv run --no-project python
"""Generate the binary Homebrew formula from a complete release SHA256SUMS."""

import argparse
import re
from pathlib import Path


def render(version, checksums, repository, base_url=None):
    version = version.removeprefix("v")
    if not re.fullmatch(r"\d+\.\d+\.\d+(?:-[A-Za-z0-9.-]+)?", version):
        raise ValueError("Expected a semantic version")
    if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", repository):
        raise ValueError("Expected repository owner/name")
    digests = {}
    for line in checksums.read_text().splitlines():
        if not line.strip():
            continue
        match = re.fullmatch(r"([0-9a-fA-F]{64})\s+\*?([^/\s]+)", line)
        if not match:
            raise ValueError(f"Invalid checksum line: {line!r}")
        if match[2] in digests:
            raise ValueError(f"Duplicate checksum for {match[2]}")
        digests[match[2]] = match[1].lower()
    base_url = (
        base_url or f"https://github.com/{repository}/releases/download/v{version}"
    )
    if any(c in base_url for c in ['"', "\n", "\r", "#{", "\\"]):
        raise ValueError("Unsafe formula URL")
    lines = [
        "# Generated by scripts/render-homebrew-formula.py; update from release SHA256SUMS.",
        "class Aviary < Formula",
        '  desc "Bird-compatible CLI for reading and posting on X"',
        f'  homepage "https://github.com/{repository}"',
        f'  version "{version}"',
        "",
    ]
    for os_name in ("macos", "linux"):
        lines.append(f"  on_{os_name} do")
        if os_name == "macos":
            lines.append("    depends_on macos: :ventura")
        for arch in ("arm64", "x86_64"):
            filename = f"aviary-{version}-{os_name}-{arch}.tar.gz"
            if filename not in digests:
                raise ValueError(
                    f"Missing checksum for {filename}; all four release archives are required"
                )
            lines.extend(
                [
                    f"    on_{'arm' if arch == 'arm64' else 'intel'} do",
                    f'      url "{base_url.rstrip("/")}/{filename}"',
                    f'      sha256 "{digests[filename]}"',
                    "    end",
                ]
            )
        lines.extend(["  end", ""])
    lines.extend(
        [
            "  def install",
            '    libexec.install Dir["*"]',
            '    bin.install_symlink libexec/"bin/aviary"',
            "  end",
            "",
            "  test do",
            '    ENV["AVIARY_SKIP_QUERY_ID_REFRESH"] = "1"',
            '    ENV["XDG_CONFIG_HOME"] = (testpath/"config").to_s',
            '    assert_match "whoami", shell_output("#{bin}/aviary --help")',
            '    assert_match "ok ", shell_output("#{libexec}/libexec/aviary-selftest --resources-only")',
            '    assert_match \'"features"\', shell_output("#{bin}/aviary query-ids --json")',
            "  end",
            "end",
            "",
        ]
    )
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True)
    parser.add_argument("--checksums", type=Path, required=True)
    parser.add_argument("--repository", default="grahamannett/aviary-swift")
    parser.add_argument(
        "--base-url",
        help="Override archive URL directory for local installer validation",
    )
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    formula = render(args.version, args.checksums, args.repository, args.base_url)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(formula)
    print(args.output)
